version: '3'

services:
    snappass:
        build: .
        image: pinterest/snappass
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=True
        depends_on:
          - redis

    redis:
        image: "redis:latest"

    nginx:
        image: "nginx"
        ports:
            - "443:443"
        depends_on:
            - snappass
        volumes:
            - ./nginx_proxy_http.conf:/etc/nginx/conf.d/nginx_proxy_http.conf
            - ./start-nginx.sh:/opt/nginx/start-nginx.sh
        command:
            - /opt/nginx/start-nginx.sh
